### ISSUE TITLE
Building failed

### ISSUE THREAD

**Issue by JamesParkDev** [RestoreMonarchy/UnturnedServersCommunity#4]
Hello while building this project I got

"C:\Users\james\Desktop\Main\Work\Servers\Web\Server\Web.Server.csproj : error NU1101: Unable to find package AspNet.Security.ApiKey.Providers. No packages exist with this id in source(s): nuget.org [C:\Users\james\Desktop\Main\Work\Servers\Web\Web.sln]"

I tried restoring, but the same error seems this package is missing from NuGet any help you can provide?

**Comment by RestoreMonarchy** [comment]
The package was sadly removed from NuGet tho I kept the dll, you can reference it instead
[AspNet.Security.ApiKey.Providers.dll.zip](https://github.com/RestoreMonarchyCommunity/Servers/files/4302127/AspNet.Security.ApiKey.Providers.dll.zip)

I'm gonna update whole project to reference that dll too later

**Comment by JamesParkDev** [comment]
Ah, I see, sorry to ask but what's the best way to reference it? I'm not really sure how to add a nonexistent NuGet package to the project.

**Comment by RestoreMonarchy** [comment]
Get rid of NuGet package reference and add reference dll like this for Web.Server.dll
![image](https://user-images.githubusercontent.com/35507241/76147251-93419400-609a-11ea-8501-f397e3d0c93b.png)

**Comment by JamesParkDev** [comment]
Yea that built the project! Also is global .sln missing? Kinda confusing since you have multiple of them but in there should be one global one? Or "Web" is an entry where I should build from

**Comment by RestoreMonarchy** [comment]
Well this repository contains projects of Web and Plugins that's why I have them separate cuz usually if I work on web I don't work on plugins and I prefer less projects in solution.

**Comment by JamesParkDev** [comment]
All works well. Thank you for your reply!
